---
title: "Metastatic_seeding"
output: html_document
date: "2024-10-11"
---

```{r message=FALSE, warning=FALSE}
library(rstatix)
library(ggpubr)
library(pals)
library(lubridate)
library(survival)
library(survminer)
library(forestmodel)
library(ggbeeswarm)
library(tidyverse)
```

import
```{r}
hist_col <- c("UC"="#815CA6","PUC"="#84C2EB","NE"="#E24D74","UC_focal"="#ACD7A0","UCSD"="#43823D","UC_UCSD"="#ACD7A0", "SARC"="#D2BEA5",
              "Founder"= "#FEC216", "Shared"= "#2B3990", "Private"= "#C91220", 
              "Targeted"="#F8766D", "WGS"="#00BFC4")
pat_col <-c('#e6194b','#3cb44b','#ffe119','#fabed4','#4363d8','#f58231','#42d4f4','#911eb4','#f032e6','#bfef45','#469990','#dcbeff','#9a6324','#fffac8','#800000','#aaffc3','#808000','#ffd8b1','#000075','#a9a9a9') %>%
  setNames(c('15-109','16-070','16-097','17-026','17-030','17-071','18-101','18-120','19-007','19-044','15-108','16-079','17-020','17-047','18-016','18-065','19-001','19-004','19-022','19-037'))
seed_col <- c("monoclonal"="palegreen2", "polyclonal_monophyletic"="plum", "monophyletic"="plum", "polyclonal_polyphyletic"="maroon", "polyphyletic"="maroon", "multi_tumor"="navy")

theme_set(theme_classic() + 
            theme(axis.text = element_text(color="black"),
                  rect = element_rect(fill = NULL),
                  axis.ticks = element_line(color="black")))

clinical <- read.csv('Supplementary_Tables/clinical_data/all_clinical_data_20260413_forSup.csv')


seeding <- read.csv('Supplementary_Tables/Metastatic_Seeding/Metastatic_seeding_summary_withTURBT.csv')
sample_CP <- read_csv('Supplementary_Tables/genomic_results/SNVs/sample_cluster_CP_withTURBT.csv', show_col_types = F)
sample_info <- read.csv('Revision_1/Supplementary_tables/all_sequencing_detailed_March2026.csv')

wd <- '/Metastatic_Seeding/withTURBT/'
figs <- "Main_Figures/Figure2/rawImages/withTURBT/"
supp <- 'Revision_1/Supplementary_Figures/Supplementary_Figure3_old2/raw_images/'
SD_main <- "Main_Figures/Figure2/source_data/"
SD_sup <- 'Revision_1/Supplementary_Figures/Supplementary_Figure3_old2/source_data/'
```

Fig 2D: stacked bar pri vs met source
```{r}
df <- seeding %>%
  group_by(seeding_source, seeding_type) %>%
  summarise(freq=n()) %>%
  mutate(seeding_source = factor(seeding_source, levels=c("primary", "met")), 
         seeding_type = factor(seeding_type, levels=c("monoclonal", "polyclonal_monophyletic", "polyclonal_polyphyletic", "multi_tumor"))) 
write.csv(df, paste0(SD_main, "2D_seeding_byPriMet.csv"), row.names = F)

df %>%
  ggplot(aes(x=seeding_source, y=freq, fill=seeding_type)) +
    geom_bar(stat="identity", position = "stack") +
    theme(legend.position = "none") +
    scale_fill_manual(values=c("palegreen2", "plum", "maroon", "navy")) +
    labs(x="Seeding from", y="# seeding events", fill="Seeding Type")
ggsave(paste0(figs, "Seeding_summary.pdf"), width=1.5, height=3)
ggsave(paste0(wd, "Seeding_summary.pdf"), width=4, height=3)

#fisher exact
df_test <- df %>% 
  mutate(seeding_type = case_match(seeding_type, "polyclonal_polyphyletic"~"polyclonal_polyphyletic", .default = "not_PP")) %>%
  group_by(seeding_source, seeding_type) %>%
  summarise(freq=sum(freq)) %>%
  pivot_wider(names_from = seeding_type, values_from = freq) %>%
  as.data.frame() %>% `rownames<-`(c("primary", "met")) %>% select(-seeding_source)
fisher.test(df_test) #p.val = 0.03789
df_test %>%
  mutate(total = not_PP + polyclonal_polyphyletic, 
         PP_prop = polyclonal_polyphyletic/total)
```

Fig 2E: stacked bar by histology
```{r}
df <- seeding %>%
  group_by(Histology, seeding_type) %>%
  summarise(freq=n()) %>%
  mutate(Histology = factor(Histology, levels=c("UC", "UCSD", "PUC", "NE", "SARC")), 
         seeding_type = factor(seeding_type, levels=c("monoclonal", "polyclonal_monophyletic", "polyclonal_polyphyletic", "multi_tumor"))) 
write.csv(df, paste0(SD_main, "2E_seeding_byHist.csv"), row.names = F)

df %>%
  ggplot(aes(x=Histology, y=freq, fill=seeding_type)) +
    geom_bar(stat="identity", position = "fill") +
    theme(legend.position = "none") +
    scale_fill_manual(values=c("palegreen2", "plum", "maroon", "navy")) +
    labs(x="Seeding from", y="# seeding events", fill="Seeding Type")
ggsave(paste0(figs, "Seeding_summary_byHistology.pdf"), width=5, height=3)
ggsave(paste0(wd, "Seeding_summary_byHistology.pdf"), width=5, height=3)

#fisher exact
## UC vs UCSD
df_test <- df %>% 
  filter(Histology %in% c("UC", "UCSD")) %>%
  mutate(seeding_type = case_match(seeding_type, "polyclonal_polyphyletic"~"polyclonal_polyphyletic", .default = "not_PP")) %>%
  group_by(Histology, seeding_type) %>%
  summarise(freq=sum(freq)) %>%
  pivot_wider(names_from = seeding_type, values_from = freq) %>%
  as.data.frame() %>% `rownames<-`(c("UC", "UCSD")) %>% select(-Histology)
fisher.test(df_test) #p.val = 0.003056
## UC vs PUC
df_test <- df %>% 
  filter(Histology %in% c("UC", "PUC")) %>%
  mutate(seeding_type = case_match(seeding_type, "polyclonal_polyphyletic"~"polyclonal_polyphyletic", .default = "not_PP")) %>%
  group_by(Histology, seeding_type) %>%
  summarise(freq=sum(freq)) %>%
  pivot_wider(names_from = seeding_type, values_from = freq) %>%
  as.data.frame() %>% `rownames<-`(c("UC", "PUC")) %>% select(-Histology)
fisher.test(df_test) #p.val = 0.04191
## UC vs NE
df_test <- df %>% 
  filter(Histology %in% c("UC", "NE")) %>%
  mutate(seeding_type = case_match(seeding_type, "polyclonal_polyphyletic"~"polyclonal_polyphyletic", .default = "not_PP")) %>%
  group_by(Histology, seeding_type) %>%
  summarise(freq=sum(freq)) %>%
  pivot_wider(names_from = seeding_type, values_from = freq) %>%
  as.data.frame() %>% `rownames<-`(c("UC", "NE")) %>% select(-Histology)
fisher.test(df_test) #p.val = 0.01449
## UC vs SARC
df_test <- df %>% 
  filter(Histology %in% c("UC", "SARC")) %>%
  mutate(seeding_type = case_match(seeding_type, "polyclonal_polyphyletic"~"polyclonal_polyphyletic", .default = "not_PP")) %>%
  group_by(Histology, seeding_type) %>%
  summarise(freq=sum(freq)) %>%
  pivot_wider(names_from = seeding_type, values_from = freq) %>%
  mutate(not_PP = case_when(is.na(not_PP)~0, .default = not_PP)) %>%
  as.data.frame() %>% `rownames<-`(c("UC", "SARC")) %>% select(-Histology)
fisher.test(df_test) #p.val = 0.003953
```


### SET UP ###

clonality complexity metrics- set up
```{r}
#number of clones per sample
clones_tumor <- sample_CP %>% filter(cellular_prevalence>0.03, !is.na(cluster_type)) %>%
  group_by(sample_id) %>%
  summarise(n_clones_tumor=n()) %>%
  mutate(patient = substr(sample_id, 1, 6)) %>%
  group_by(patient) %>%
  summarise(avg_clones_tumor = mean(n_clones_tumor), 
            med_clones_tumor = median(n_clones_tumor))

#average CP of clusters in tumor
avg_CP_df <-  sample_CP %>% filter(cellular_prevalence>0.03, cluster_type %in% c("Founder", "Shared", "Private")) %>%
  group_by(sample_id) %>%
  summarise(avg_CP = mean(cellular_prevalence)) %>%
  mutate(patient = substr(sample_id, 1, 6)) %>%
  group_by(patient) %>%
  summarise(avg_CP = mean(avg_CP))
avg_CP_pertumor <-  sample_CP %>% filter(cellular_prevalence>0.03, cluster_type %in% c("Founder", "Shared", "Private")) %>%
  group_by(sample_id) %>%
  summarise(avg_CP = mean(cellular_prevalence)) %>%
  mutate(patient = substr(sample_id, 1, 6)) 

hist_df <- sample_info %>% filter(tissue_type!="Normal") %>%
  select(patient, hist_patient, UC_percent) %>%
  group_by(patient) %>%
  summarize(Histology = unique(hist_patient), 
            UC_percent_avg = mean(UC_percent), 
            UC_percent_med = median(UC_percent), .groups = "drop") %>%
  mutate(Histology = case_match(Histology, "UC-Sarc"~"SARC", .default = Histology))
```


### SURVIVAL ###

set up time: dx to met, met to death, dx to death
```{r}
pat_clone <- seeding %>%
  group_by(patient) %>%
  summarise(seeding_clones = sum(seeding_clones), 
            seeding_events = n()) %>% ungroup()

pat_tumor <- seeding %>%
  distinct(patient, block_letter) %>%
  group_by(patient) %>%
  summarise(n_mets = n()) %>% ungroup() %>%
  mutate(n_tumors = n_mets + 1)

pat_type <- seeding %>%
  group_by(patient, seeding_type) %>%
  summarise(freq = n()) %>% ungroup() %>%
  pivot_wider(names_from = seeding_type, values_from = freq)

pat_seeding <- pat_clone %>%
  left_join(pat_tumor) %>%
  mutate(clones_perMet = seeding_clones/n_mets, 
         clones_perTumor = seeding_clones/n_tumors, 
         clones_perEvent = seeding_clones/seeding_events) %>%
  left_join(pat_type) %>%
  left_join(hist_df) %>%
  left_join(clinical %>% select(Patient, Survival_from_Dx_years, Survival_from_metastasis_yrs, dx_to_met_months, total_treatments, Age_Dx, Sex), by=c("patient"="Patient")) %>%
  left_join(clones_tumor) %>%
  left_join(avg_CP_df) %>%
  mutate(monoclonal = case_when(is.na(monoclonal)~0, .default = monoclonal), 
         multi_tumor = case_when(is.na(multi_tumor)~0, .default = multi_tumor), 
         polyclonal_monophyletic = case_when(is.na(polyclonal_monophyletic)~0, .default = polyclonal_monophyletic), 
         polyclonal_polyphyletic = case_when(is.na(polyclonal_polyphyletic)~0, .default = polyclonal_polyphyletic), 
         polyclonal = polyclonal_monophyletic + polyclonal_polyphyletic)

df <- pat_seeding %>%
  mutate(PP_prop_mets = polyclonal_polyphyletic/n_mets,
         PP_prop_events = polyclonal_polyphyletic/seeding_events,
         P_prop_events = polyclonal_polyphyletic/seeding_events,
         P_prop_mets = polyclonal/n_mets,
         Histology = factor(Histology, levels=c("UC", "PUC", "UCSD", "NE", "SARC")),
         Sex = factor(Sex, levels=c("M", "F"))) %>%
  filter(patient !="16-070")

df_min <- df %>%
  select(patient, seeding_clones, n_mets, clones_perMet, Histology:UC_percent_avg, Survival_from_metastasis_yrs, Age_Dx, Sex)
#write.csv(df_min, paste0(SD_main, "2BC_clones_perMet_survival_Cox_covariates.csv"), row.names = F)
```

KM with continuous # seeding clones **Fig 2B/C**
```{r}
#clones_perMet + Histology + Age + Sex
cox_model <- coxph(Surv(time = df$Survival_from_metastasis_yrs)~clones_perMet + Histology + Age_Dx + Sex, data = df)
summary(cox_model) #0.0910 
forest_plot <- forest_model(cox_model)
forest_plot
ggsave(plot=forest_plot, paste0(wd, "Clinical_correlations/Forest_clones_perMet_AgeSex_SurvfromMet_updatedClinical.pdf"), width=8, height=4)
ggsave(plot=forest_plot, paste0(figs, "Clinical_correlations/Forest_clones_perMet_AgeSex_SurvfromMet_updatedClinical.pdf"), width=8, height=4)
ggsave(plot=forest_plot, paste0(supp, "Clinical_correlations/Forest_clones_perMet_AgeSex_SurvfromMet_updatedClinical.pdf"), width=8, height=4)

#calculate + split on risk (full clones + histology)
df_risk <- df %>%
  filter(!is.na(Survival_from_metastasis_yrs)) %>%
  mutate(risk = predict(cox_model, type="lp"), 
         risk_group = case_when(risk > median(risk)~"high_risk", .default = "low_risk"))
write.csv(df_risk, paste0(SD_main, "2C_Cox_risk_scores_updatedClinical.csv"), row.names = F)

KM <- Surv(time=df_risk$Survival_from_metastasis_yrs)
surv_diff <- survdiff(KM ~ risk_group, data = df_risk)
surv_diff #p= 7e-04 
fit <- survfit(KM ~ risk_group, data=df_risk)
p <- ggsurvplot(fit=fit, data=df_risk,
           pval=F, conf.int = F, risk.table = T, 
           ylab="Survival from Met", xlab="Years", color = "risk_group", palette = c("snow3", "black"))
p
ggsave(plot=p$plot, paste0(wd, "Clinical_correlations/KM_clones_perMet_SurvfromMet_AgeSex_KM_updatedClinical.pdf"),width=6, height=6)
ggsave(plot=p$plot, paste0(figs, "Clinical_correlations/KM_clones_perMet_SurvfromMet_AgeSex_KM_updatedClinical.pdf"), width=5, height=6)
```

compare to hist/age/sex without seeding **Sup Fig 3B**
```{r}
# Histology + Age + Sex
cox_model <- coxph(Surv(time = df$Survival_from_metastasis_yrs)~ Histology + Age_Dx + Sex, data = df)
summary(cox_model) 
forest_plot <- forest_model(cox_model)
forest_plot
ggsave(plot=forest_plot, paste0(wd, "Clinical_correlations/Forest_AgeSex_SurvfromMet_updatedClinical.pdf"), width=8, height=4)
ggsave(plot=forest_plot, paste0(supp, "Clinical_correlations/Forest_AgeSex_SurvfromMet_updatedClinical.pdf"), width=8, height=4)

#calculate + split on risk
df_risk <- df %>%
  filter(!is.na(Survival_from_metastasis_yrs)) %>%
  mutate(risk = predict(cox_model, type="lp"), 
         risk_group = case_when(risk > median(risk)~"high_risk", .default = "low_risk")) %>%
  select(patient, Histology, Age_Dx, Sex, Survival_from_metastasis_yrs, risk_group)
write.csv(df_risk, paste0(SD_sup, "S3B_baseModel_KM_riskSplit.csv"), row.names = F)

KM <- Surv(time=df_risk$Survival_from_metastasis_yrs)
surv_diff <- survdiff(KM ~ risk_group, data = df_risk)
surv_diff #p= 0.008
fit <- survfit(KM ~ risk_group, data=df_risk)
p <- ggsurvplot(fit=fit, data=df_risk,
           pval=F, conf.int = F, risk.table = T, 
           ylab="Survival from Met", xlab="Years", color = "risk_group", palette = c("snow3", "black"))
p
ggsave(plot=p$plot, paste0(wd, "Clinical_correlations/KM_SurvfromMet_AgeSex_KM_updatedClinical.pdf"),width=6, height=6)
ggsave(plot=p$plot, paste0(supp, "Clinical_correlations/KM_SurvfromMet_AgeSex_KM_updatedClinical.pdf"), width=5, height=6)
```

clones per met w/ UC_percent **Sup Fig 3C**
```{r}
#clones_perMet + UC_percent + Age + Sex
cox_model <- coxph(Surv(time = df$Survival_from_metastasis_yrs)~ clones_perMet + UC_percent_avg + Age_Dx + Sex, data = df)
summary(cox_model) 
forest_plot <- forest_model(cox_model)
forest_plot
ggsave(plot=forest_plot, paste0(wd, "Clinical_correlations/Forest_clones_perMet_UCpercent_AgeSex_SurvfromMet_updatedClinical.pdf"), width=8, height=4)
ggsave(plot=forest_plot, paste0(supp, "Clinical_correlations/Forest_clones_perMet_UCpercent_AgeSex_SurvfromMet_updatedClinical.pdf"), width=8, height=4)

#calculate + split on risk
df_risk <- df %>%
  filter(!is.na(Survival_from_metastasis_yrs)) %>%
  mutate(risk = predict(cox_model, type="lp"), 
         risk_group = case_when(risk > median(risk)~"high_risk", .default = "low_risk")) %>%
  select(patient, seeding_clones, clones_perMet, Survival_from_metastasis_yrs, Histology, UC_percent_avg, Age_Dx, Sex, risk, risk_group) %>%
  rename(avg_polyclonality_seeding = clones_perMet)
write.csv(df_risk, paste0(SD_sup, "S3C_KM_percentUC_riskSplit.csv"), row.names = F)

KM <- Surv(time=df_risk$Survival_from_metastasis_yrs)
surv_diff <- survdiff(KM ~ risk_group, data = df_risk)
surv_diff #p= 0.008
fit <- survfit(KM ~ risk_group, data=df_risk)
p <- ggsurvplot(fit=fit, data=df_risk,
           pval=F, conf.int = F, risk.table = T, 
           ylab="Survival from Met", xlab="Years", color = "risk_group", palette = c("snow3", "black"))
p
ggsave(plot=p$plot, paste0(wd, "Clinical_correlations/KM_SurvfromMet_UCpercent_AgeSex_KM_updatedClinical.pdf"),width=6, height=6)
ggsave(plot=p$plot, paste0(supp, "Clinical_correlations/KM_SurvfromMet_UCpercent_AgeSex_KM_updatedClinical.pdf"), width=5, height=6)
```


### TREATMENT DIFFERENCES ###

IO + chemo **Sup Fig 3D**
```{r}
IO <- clinical %>% select(Patient, PDL1_inhibitor, PD1_inhibitor) %>%
  rename(patient = Patient) %>%
  mutate(any_IO = case_when(PDL1_inhibitor == "Y"~"Y", 
                            PD1_inhibitor == "Y"~"Y", 
                            .default = "N"))

chemo <- clinical %>% select(Patient, 
                             gemcitabine_alone, Docetaxel_Taxotere, Paclitaxel_Taxol_Alone, gemcitabine_and_carboplatin, Gemcitabine_and_Paclitaxel, 
                             gemcitabine_and_cisplatin, Cisplatin_alone, Etoposide_and_Cisplatin, aMVAC) %>%
  rowwise() %>%
  mutate(num_chemo = sum(c_across(gemcitabine_alone:aMVAC)=="Y"), 
         num_cisplatin = sum(c_across(gemcitabine_and_cisplatin:aMVAC)=="Y"))  %>%
  mutate(any_chemo = ifelse(num_chemo>0, "Y", "N"),
         any_cisplatin = ifelse(num_cisplatin>0, "Y", "N"))%>% ungroup()
  

IO_chemo <- IO %>% select(patient, any_IO) %>%
  left_join(chemo %>% select(Patient, any_chemo), by=c("patient"="Patient")) %>%
  mutate(combo = case_when(any_IO=="Y"&any_chemo=="Y"~"both", 
                           any_IO=="Y"&any_chemo=="N"~"IO_only", 
                           any_IO=="N"&any_chemo=="Y"~"chemo_only", 
                           .default = "none"), 
         seeding = case_when(patient %in% seeding$patient~"Yes", .default = "No"))

IO_chemo_seeding <- pat_seeding %>%
  left_join(IO_chemo) %>%
  select(patient, monoclonal:polyclonal_polyphyletic, any_IO, any_chemo, combo)
write.csv(IO_chemo_seeding, paste0(SD_sup, "S3D_SeedingEvents_byIOChemo.csv"), row.names = F)

#graph
IO_chemo_seeding %>%
  mutate(combo = factor(combo, levels=c("none", "chemo_only", "both", "IO_only"))) %>%
  distinct(combo, patient) %>% select(combo) %>% table()

IO_chemo_seeding %>%
  mutate(combo = factor(combo, levels=c("none", "chemo_only", "both", "IO_only"))) %>%
  pivot_longer(cols=monoclonal:polyclonal_polyphyletic, names_to = "seeding_type", values_to = "freq") %>%
  ggplot(aes(x=combo, y=freq, fill=seeding_type)) +
    geom_bar(stat="identity", position="fill") +
    scale_x_discrete(labels=c("none\nn=2", "chemo_only\nn=4", "both\nn=7", "IO_only\nn=3"), name = NULL) +
    labs(y="Proportion Seeding Events") +
    scale_fill_manual(values=c("palegreen2", "plum", "maroon")) +
    theme(legend.position = "none") 
ggsave(paste0(wd, "SeedingType_byIOChemo.pdf"), width=3.5, height=3)
ggsave(paste0(supp, "SeedingType_byIOChemo.pdf"), width=3.5, height=3)
```




