samples: # structure is [__path_to_sample___, __normal_sample_name___, __path_to_normal___]
    sample1: [path/to/sample1/___sample1___.bam, /normal/name/matching/bam_header/, /path/to/normal/___normal___.bam]
    sample2: ...
    sample3: ...
